// --- Day 8: Resonant Collinearity ---
// https://adventofcode.com/2024/day/8

import 'dart:io';
import 'package:advent_of_code_2024/day08.dart';
import 'package:advent_of_code_2024/util.dart';
import 'package:test/test.dart';

final input = File('test/data/day08.txt').readAsLinesSync();

void main() {
  group('Part One', () {
    test('Example 1', () {
      expect(
        solveA(
          r'''
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
'''
              .toLinesList(),
        ),
        equals(14),
      );
    });
    test('Solution', () {
      expect(solveA(input), equals(423));
    });
  });
  group('Part Two', () {
    test('Example 1', () {
      expect(
        solveB(
          r'''
T.........
...T......
.T........
..........
..........
..........
..........
..........
..........
..........
'''
              .toLinesList(),
        ),
        equals(9),
      );
    });
    test('Example 2', () {
      expect(
        solveB(
          r'''
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
'''
              .toLinesList(),
        ),
        equals(34),
      );
    });
    test('Solution', () {
      expect(solveB(input), equals(1287));
    });
  });
}
